AWSTemplateFormatVersion: "2010-09-09"
Description: Provides the core resources for the contextual chat application

Parameters:
  ApplicationName:
    Type: String
    Description: The name of your application
    AllowedPattern: "^[a-zA-Z0-9-]+$"
  EmbeddingModelArn:
    Type: String
    Description: Arn of the model used to create vector embeddings for the knowledge base Bedrock Knowledge base ID
    AllowedPattern: "^arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}:(([0-9]{12}:custom-model/[a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}/[a-z0-9]{12})|(:foundation-model/[a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}))$"
    Default: "arn:aws:bedrock:us-east-1::foundation-model/amazon.titan-embed-text-v1"


Resources:

  KnowledgeBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Join [ "-", !Ref ApplicationName, "knowledge-base-bucket" ]

  KnowledgeBase:
    Type: AWS::Bedrock::KnowledgeBase
    DeletionPolicy: Delete
    Properties:
      Name: !Join [ "-", !Ref ApplicationName, "knowledge-base" ]
      Description: "A knowledge base for the contextual chatbot application"
      RoleArn: !GetAtt KnowledgeBaseRole.Arn
      KnowledgeBaseConfiguration: 
        Type: VECTOR
        VectorKnowledgeBaseConfiguration:
          EmbeddingModelArn: !Ref EmbeddingModelArn
      StorageConfiguration: 
        Type: OPENSEARCH_SERVERLESS
  
  KnowledgeBaseRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: [ "-", !Ref ApplicationName, "knowledge-base-role" ]
      Description: "A role for the Amazon Bedrock knowledge base to access it"s data sources"
      Policies:
        - PolicyName: Bedrock
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: "BedrockInvokeModelStatement"
                Effect: Allow
                Action:
                  - "bedrock:InvokeModel"
                Resource:
                  - !Ref EmbeddingModelArn
        - PolicyName: OpenSearch
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: "OpenSearchServerlessAPIAccessAllStatement"
                Effect: Allow
                Action:
                  - "aoss:APIAccessAll"
                Resource:
                  - !Sub "arn:${AWS::Partition}:aoss:${AWS::Region}:${AWS::AccountId}:collection/*"
        - PolicyName: S3
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: "S3ListBucketStatement"
                Effect: Allow
                Action:
                  - "s3:ListBucket"
                Resource:
                  - !Sub "arn:${AWS::Partition}:s3:::${KnowledgeBucket}"
                Condition:
                  StringEquals:
                      "aws:ResourceAccount": !Ref AWS::AccountId
        
             - Sid: "S3GetObjectStatement"
                Effect: Allow
                Action:
                  - "s3:GetObject"
                Resource:
                  - !Sub "arn:${AWS::Partition}:s3:::${KnowledgeBucket}/*"
                Condition:
                  StringEquals:
                      "aws:ResourceAccount": !Ref AWS::AccountId
